export {
  ExchangeRateUnavailableError,
  defaultOracleClient,
  refreshRate,
  getExchangeRate,
  invalidateRate,
  rateKey,
  lastGoodRateKey,
  getCacheMetrics,
  resetCacheMetrics,
  getExchangeRateCacheConfig,
  setExchangeRateCacheConfig,
  resetExchangeRateCacheConfig,
  exchangeRateConfigFromEnv,
  getExchangeRateHealth,
  startRateRefreshScheduler,
  setRateOracleClient,
  resetRateOracleClient,
  _setRateRedisClientForTesting,
  _resetRateRedisClientForTesting,
  type ExchangeRateRecord,
  type ExchangeRateResult,
  type RateOracleClient,
  type ExchangeRateCacheConfig,
  type CacheMetrics,
  type RateCacheRedisClient,
  type RateRefreshSchedulerHandle,
} from "./exchangeRateCache.js";

export {
  CircuitBreaker,
  CircuitBreakerOpenError,
  getRateOracleCircuitBreaker,
  setRateOracleCircuitBreaker,
  resetRateOracleCircuitBreakerForTesting,
  type CircuitState,
  type CircuitBreakerConfig,
  type CircuitBreakerStats,
} from "./circuitBreaker.js";
